# Generated by Django 5.2.13 on 2026-05-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefone1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefone2',
        ),
        migrations.AddField(
            model_name='user',
            name='telephone1',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telephone 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone2',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telephone 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, verbose_name='Full profile status'),
        ),
    ]
