# Generated by Django 5.2.13 on 2026-05-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0002_remove_user_telefone1_remove_user_telefone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, verbose_name='Indicador de perfil completo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone1',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone2',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone 2'),
        ),
    ]
