# Generated by Django 5.2.13 on 2026-05-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0003_alter_user_cpf_alter_user_profile_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 2'),
        ),
    ]
