# Generated by Django 5.2.13 on 2026-05-15 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0004_alter_user_cpf_alter_user_telephone1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('abbr', models.CharField(max_length=10, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='EventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria do evento',
                'verbose_name_plural': 'Categorias dos eventos',
            },
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Função do evento',
                'verbose_name_plural': 'Funções do evento',
            },
        ),
        migrations.CreateModel(
            name='EventStagesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_stage_type_name', models.CharField(max_length=255, verbose_name='Nome da etapa')),
            ],
            options={
                'verbose_name': 'Tipo de etapa',
                'verbose_name_plural': 'Tipos de etapas',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, verbose_name='Idioma')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='NotificationsSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_subject', models.CharField(max_length=255, verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Assunto da notificação',
                'verbose_name_plural': 'Assuntos das notificações',
            },
        ),
        migrations.CreateModel(
            name='EventAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255, verbose_name='Nome do local')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_addresses', to='sympo_track_app.city', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Endereço do evento',
                'verbose_name_plural': 'Endereços dos eventos',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('subject', models.CharField(max_length=255, verbose_name='Tema')),
                ('external_link', models.URLField(verbose_name='Link externo')),
                ('is_public', models.BooleanField(default=True, verbose_name='Evento público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sympo_track_app.eventaddress', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventCategoryRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sympo_track_app.eventcategories', verbose_name='Categoria')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sympo_track_app.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Relação de categoria',
                'verbose_name_plural': 'Relações de categorias',
                'unique_together': {('category', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(through='sympo_track_app.EventCategoryRel', to='sympo_track_app.eventcategories', verbose_name='Categorias'),
        ),
        migrations.CreateModel(
            name='EventPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROFISSIONAL', 'Profissional'), ('POS', 'Pós-graduação'), ('GRADUACAO', 'Graduação')], max_length=100, verbose_name='Categoria')),
                ('batch', models.CharField(default='Lote 1', max_length=50, verbose_name='Lote')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sympo_track_app.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Preço do evento',
                'verbose_name_plural': 'Preços do evento',
            },
        ),
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Data inicial')),
                ('end_date', models.DateTimeField(verbose_name='Data final')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sympo_track_app.event', verbose_name='Evento')),
                ('stage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sympo_track_app.eventstagestype', verbose_name='Tipo da etapa')),
            ],
            options={
                'verbose_name': 'Etapa do evento',
                'verbose_name_plural': 'Etapas do evento',
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('EXPIRADO', 'Expirado')], max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='sympo_track_app.event', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.TextField(verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_reasons', to='sympo_track_app.eventsubscription', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Motivo de cancelamento',
                'verbose_name_plural': 'Motivos de cancelamento',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sympo_track_app.language', verbose_name='Idioma'),
        ),
        migrations.CreateModel(
            name='ManagementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_groups', to='sympo_track_app.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Grupo de gestão',
                'verbose_name_plural': 'Grupos de gestão',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sympo_track_app.notificationssubject', verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('uf', models.CharField(max_length=10, verbose_name='UF')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='sympo_track_app.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='sympo_track_app.state', verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='UserStageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('event_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_requirements', to='sympo_track_app.eventstage', verbose_name='Etapa do evento')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sympo_track_app.eventsubscription', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Requisito da etapa',
                'verbose_name_plural': 'Requisitos das etapas',
            },
        ),
        migrations.CreateModel(
            name='ManagementGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sympo_track_app.managementgroup', verbose_name='Grupo')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sympo_track_app.eventrole', verbose_name='Função')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro do grupo',
                'verbose_name_plural': 'Membros dos grupos',
                'unique_together': {('group', 'user', 'role')},
            },
        ),
    ]
