# Generated by Django 5.2.13 on 2026-07-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0005_city_country_eventcategories_eventrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategoriesArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('college', models.CharField(choices=[('EXATAS', 'COLÉGIO DE CIÊNCIAS EXATAS, TECNOLÓGICAS E MULTIDISCIPLINAR'), ('HUMANAS', 'COLÉGIO DE HUMANIDADES'), ('VIDA', 'COLÉGIO DE CIÊNCIAS DA VIDA')], max_length=8, verbose_name='Colégio')),
            ],
        ),
        migrations.AddField(
            model_name='eventcategories',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sympo_track_app.eventcategoriesarea', verbose_name='Área'),
        ),
    ]
