# Generated by Django 5.2.13 on 2026-07-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0006_eventcategoriesarea_eventcategories_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategoriesarea',
            options={'verbose_name': 'Área de categoria do evento', 'verbose_name_plural': 'Áreas de categorias dos eventos'},
        ),
    ]
