# Generated by Django 5.2.13 on 2026-07-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0007_alter_eventcategoriesarea_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventstagestype',
            old_name='event_stage_type_name',
            new_name='name',
        ),
    ]
