# Generated by Django 5.2.13 on 2026-07-10 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0008_rename_event_stage_type_name_eventstagestype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementgroupmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Proprietário'), ('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('EDITOR', 'Editor'), ('VIEWER', 'Visualizador')], default='VIEWER', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='managementgroupmember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='managementgroup',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_groups', to='sympo_track_app.managementgroup', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='managementgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='managementgroup',
            name='members',
            field=models.ManyToManyField(related_name='management_groups', through='sympo_track_app.ManagementGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managementgroup',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AddField(
            model_name='managementgroupmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managementgroup',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='managementgroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='sympo_track_app.managementgroup', verbose_name='Grupo'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsubscription',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='managementgroupmember',
            unique_together={('group', 'user')},
        ),
        migrations.DeleteModel(
            name='EventRole',
        ),
    ]
