# Generated by Django 5.2.13 on 2026-07-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0009_alter_managementgroupmember_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementgroup',
            name='owner',
        ),
    ]
