# Generated by Django 5.2.13 on 2026-07-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0010_remove_managementgroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubscription',
            name='status',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status'),
        ),
    ]
