# Generated by Django 5.2.13 on 2026-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0011_alter_eventsubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=155, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='NotificationsSubject',
        ),
    ]
