# Generated by Django 5.2.13 on 2026-07-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0012_alter_notification_subject_alter_notification_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstagerequirement',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='sympo_track_app.eventsubscription', verbose_name='Inscrição'),
        ),
    ]
