# Generated by Django 5.2.13 on 2026-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0013_alter_userstagerequirement_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationreason',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='cancellationreason',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='cancellationreason',
            name='reason_text',
            field=models.CharField(max_length=100, verbose_name='Motivo'),
        ),
    ]
