# Generated by Django 5.2.13 on 2026-07-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0014_cancellationreason_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubscription',
            name='status',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('FINALIZADO', 'Finalizado'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status'),
        ),
    ]
