# Generated by Django 5.2.13 on 2026-07-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0015_alter_eventsubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementgroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
