# Generated by Django 5.2.13 on 2026-07-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo_track_app', '0016_alter_managementgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementgroupmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='managementgroupmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='managementgroupmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Proprietário'), ('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('VIEWER', 'Visualizador')], default='VIEWER', max_length=20, verbose_name='Cargo'),
        ),
    ]
